server:
  port: 8082
  shutdown: graceful

spring:
  application:
    name: ecommerce-prod
  config:
    activate:
      on-profile: prod
  lifecycle:
    timeout-per-shutdown-phase: 60s
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 20
      connection-timeout: 5000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
        show_sql: false
        generate_statistics: false
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true

logging:
  level:
    root: error
    com.ecommerce: warn
    org.springframework: error
    org.hibernate: error