server:
  port: 8080
  shutdown: graceful # Graceful Shutdown 기능 적용 (immediate: 즉시 요청 처리 중단 | graceful: 현재 요청 끝날때까지 기다렸다가 종료)

spring:
  application:
    name: ecommerce-local
  config:
    activate:
      on-profile: local
  lifecycle:
    timeout-per-shutdown-phase: 30s # shutdown을 최대 몇초동안 기다릴지, 해당 시간 지나면 강제 종료
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecommerce?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    hikari: # HikariCP(Connection Pool Opensource) -> JDBC Connection Pool 구현체 -> https://dkswnkk.tistory.com/685
      maximum-pool-size: 10 # 최대 커넥션 풀 크기
      minimum-idle: 5 # 최소 유휴 커넥션 수
      connection-timeout: 5000 # 커넥션 획득 최대 대기 시간(ms)
      idle-timeout: 600000 # 유후 커넥션 최대 유지 시간(ms)
      max-lifetime: 1800000 # 커넥션 최대 수명(ms)
  jpa:


logging:
  level:
    root: info
    com.ecommerce: debug
    org.springframework: info