spring:
  config:
    activate:
      on-profile: secret
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/sandbox-ecommerce?serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
