# Local
custom_local:
  db:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecommerce?useSSL=false&characterEncoding=UTF-8
    username: ecommerce_admin
    password: admin1234!

# Dev
# TODO: DEV DB
#custom_dev:
#  db:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/ecommerce?useSSL=false&characterEncoding=UTF-8
#    username: admin
#    password: admin1234!

# Prod
# TODO: PROD DB