USE `farm-market`;

-- ------------------------------------------------------------
-- Dummy data reset script
-- - Purpose: clear existing ecommerce sample data before reload
-- - Note: run this file first
-- ------------------------------------------------------------

select @@autocommit;

SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE TB_CART_ITEM;
TRUNCATE TABLE TB_CART;
TRUNCATE TABLE TB_DELIVERY;
TRUNCATE TABLE TB_PAYMENT;
TRUNCATE TABLE TB_ORDER_ITEM;
TRUNCATE TABLE TB_ORDER;
TRUNCATE TABLE TB_MEMBER_ADDRESS;
TRUNCATE TABLE TB_MEMBER_ROLE;
TRUNCATE TABLE TB_PRODUCT_IMAGE;
TRUNCATE TABLE TB_PRODUCT;
TRUNCATE TABLE TB_MEMBER;
TRUNCATE TABLE TB_ROLE;

ALTER TABLE TB_CART_ITEM AUTO_INCREMENT = 1;
ALTER TABLE TB_CART AUTO_INCREMENT = 1;
ALTER TABLE TB_DELIVERY AUTO_INCREMENT = 1;
ALTER TABLE TB_PAYMENT AUTO_INCREMENT = 1;
ALTER TABLE TB_ORDER_ITEM AUTO_INCREMENT = 1;
ALTER TABLE TB_ORDER AUTO_INCREMENT = 1;
ALTER TABLE TB_MEMBER_ADDRESS AUTO_INCREMENT = 1;
ALTER TABLE TB_MEMBER_ROLE AUTO_INCREMENT = 1;
ALTER TABLE TB_PRODUCT_IMAGE AUTO_INCREMENT = 1;
ALTER TABLE TB_PRODUCT AUTO_INCREMENT = 1;
ALTER TABLE TB_MEMBER AUTO_INCREMENT = 1;
ALTER TABLE TB_ROLE AUTO_INCREMENT = 1;

SET FOREIGN_KEY_CHECKS = 1;
